### ISSUE TITLE
With viewport zoomed the underline doubles

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvec.org#113]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/283441/64329180-1b04f380-cfcf-11e9-9be0-c794b3af179c.png">

**Comment by Aprillion** [comment]
I was able to reproduce in multiple browsers:
* zoom to max
* trigger `:hover` or `:focus` style in dev tools (or mouse hover on desktop / tap and go back on mobile)

Working on a fix at Mšené sprint.
