### ISSUE TITLE
Přidat NumFocus

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvec.org#183]
Myslím, že bychom mohli přidat NumFocus do této sekce, jestli si PyDaťáci myslí, že je to dobrý nápad:

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/283441/99519473-3a98f980-2992-11eb-84d7-a4070cd5e8de.png">

@janpipek @coobas @kokes

**Comment by kokes** [comment]
Zní dobře. (Pro kontext přidávám link na předchozí PR: #182.)

**Comment by honzajavorek** [comment]
Fixed by https://github.com/pyvec/pyvec.org/pull/185 and https://github.com/pyvec/pyvec.org/pull/186, thanks!

**Comment by janpipek** [comment]
Já díky.

**Comment by coobas** [comment]
Díky 👍
