### ISSUE TITLE
Rozpadlá mřížka

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvec.org#184]
Momentálně na webu máme takové číslo podporovaných aktivit, že se v prohlížeči na desktopu rozpadla mřížka:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/283441/99519804-9e232700-2992-11eb-803b-3ff5f0fbcf2d.png">

Na mobilu je to samozřejmě jedno. Dá se to vyřešit tak, že jednu věc odebereme, nebo že dvě přidáme. Návrhy?

**Comment by honzajavorek** [comment]
Mě napadlo jen to, že Django Girls už prakticky neděláme, takže bychom je asi mohli odstranit. Naopak bych je neodstraňoval ze sekce "Spolupracujeme", protože kdyby někdo přišel, že chce DG event udělat, nebo jakýkoliv event podle DG materiálů, tak rádi pomůžeme. Taky vidím hodnotu v DG návodu a kdo by jej chtěl dopřekládat do Češtiny či aktualizovat, podporu Pyvce mít taky bude.

**Comment by messa** [comment]
Nebo upravit layout: 
![image](https://user-images.githubusercontent.com/115487/99521513-ca3fa780-2994-11eb-9615-1c678d03632a.png)

**Comment by frenzymadness** [comment]
Jsem pro DG odebrat. Přeci jen už ani nepamatuji, kdy se takový workshop konal naposledy.

Vlastně bych si asi vzpomněl, vezl jsem při té příležitosti z Olomouce do Brna samolepky a bylo to před nějakou konferencí a už je to velmi dávno (tiskárna už neexistuje a její majitel stihl vyměnit další tři profese :smile:).
