### ISSUE TITLE
pyvec.org does not use HTTPS by default

### ISSUE THREAD

**Issue by hroncok** [pyvec/pyvec.org#305]
When I type pyvec.org to my browser URL and hit <kdb>Enter</kdb>, I end up at http://pyvec.org/ and I am not redirected to https://pyvec.org/ -- I consider that a problem.

**Comment by honzajavorek** [comment]
I checked the checkbox. Thanks!

<img width="712" alt="Screenshot 2022-09-26 at 13 49 36" src="https://user-images.githubusercontent.com/283441/192269088-298abd7f-8961-403c-98af-466bb87f5ea8.png">
