### ISSUE TITLE
PayPal button

### ISSUE THREAD

**Issue by encukou** [pyvec/pyvec.org#37]
V diskuzi o pyvec.org, ze které vzešla aktuální verze webu, byl návrh udělat tlačítko na přispění přes PayPal. Zatím tu není.

@honzajavorek z pyvec/zapojse#1:
> velkej PayPal button :smile:

**Comment by honzajavorek** [comment]
Ještě by to chtělo darujme.cz, které je pro ČR relevantnější. Jako
prerekvizitu vidím dokončení administrativního revivu neziskovky.

**Comment by honzajavorek** [comment]
Dovolil bych si to zavřít, protože jsem autorem nápadu a zároveň si dnes už nemyslím, že je to aktuální.

Pro účetní je to možná komplikace, musí se to s ní domluvit. Darujme.cz vyžaduje výroční zprávy, které chceme dělat, ale zatím se to dělat učíme. Pokud to nebudeme silně propagovat, nikdo jen tak přispívat nebude (vlastní zkušenost). Aby to mělo nějaký smysl, měli bychom mít proč to dělat, což nemáme (peníze jsou na účtě, vydělat je jsme schopni jednorázovými akcemi nebo spoluprací s firmami, a [grantů](https://github.com/pyvec/money) není tolik, abychom potřebovali nutně další z příspěvků).

Pokud by to aktuální v budoucnu bylo, určitě je možné darujme.cz nebo PayPal button rozjet, ale je dobré se domluvit s účetní, jak to bude fungovat, a hlavně vědět, za jakým účelem to chceme rozjet. Plus kdyby bylo zle, je tu ještě instrument členských příspěvků, který funguje podobně, ale bez externích služeb a administrativy navíc.
