### ISSUE TITLE
Nefunguje odkaz na transparentní účet z anglické verze webu

### ISSUE THREAD

**Issue by mikicz** [pyvec/pyvec.org#41]
Z nějakého důvodu nefunguje odkaz na transparentní účet z anglické verze webu, i když oproti odkazu na české verzi má jen `&l=ENGLISH` navíc. FIO má na transparentní účty novou adresu, český v pohodě přesměruje na novou, ale ten anglický odkaz mě místo toho hodí na stránku, že logout byl úspěšný.

Staré URL:
```
https://www.fio.cz/scgi-bin/hermes/dz-transparent.cgi?ID_ucet=2600260438
https://www.fio.cz/scgi-bin/hermes/dz-transparent.cgi?ID_ucet=2600260438&l=ENGLISH
```

Nové URL:
```
https://ib.fio.cz/ib/transparent?a=2600260438
https://ib.fio.cz/ib/transparent?a=2600260438&l=ENGLISH
```

Nejjednodušší by asi bylo jednoduše ty odkazy nahradit novou adresou, můžu poslat o víkendu PR.

**Comment by honzajavorek** [comment]
Jestli se ti povede dešifrovat na jaké adrese to Fio zobrazí v angličtině a
jestli jsou teď nové adresy, tak to bys byl úplně uzasnej kdybys to poslal
jako PR.

**Comment by mikicz** [comment]
Koukám, že v emailu se ten popisek zobrazil divně, nové adresy vím, včetně zobrazování v AJ:

Česká verze:
```
https://ib.fio.cz/ib/transparent?a=2600260438
```

Anglická verze:
```
https://ib.fio.cz/ib/transparent?a=2600260438&l=ENGLISH
```
