### ISSUE TITLE
Page build warning (DNS)

### ISSUE THREAD

**Issue by hroncok** [pyvec/pyvec.org#51]
Got an e-mail from GitHub:

The page build completed successfully, but returned the following warning for the `gh-pages` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/using-a-custom-domain-with-github-pages/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by encukou** [comment]
@honzajavorek, já se do nové Domena.cz nepřihlásím. Plánuju si od tebe vzít heslo/instrukce, až se uvidíme (nejdřív asi na březnovém Pyvu v Praze). Mám to řešit dřív?

**Comment by honzajavorek** [comment]
No ted jsem to zkusil a ja taky ne.

**Comment by honzajavorek** [comment]
Zazadal jsem o novy heslo, ale nejspis to nechodi na info@pyvec.org, ale na board@pyvec.org. Nevim.

**Comment by honzajavorek** [comment]
Poslu ti nove heslo.

**Comment by hroncok** [comment]
Any progress here? @pyvecpusher is still getting this e-mail on each Travis CI deploy.

**Comment by honzajavorek** [comment]
The issue is that we can't easily modify the DNS ourselves as the domain uses @whit's DNS servers. Solutions:

1. We could set the domain to use our domain provider's DNS servers an to get a full control over the DNS, but that could break everything set up for the domain (such as info@pyvec.org and possibly the whole GSuite, which doesn't seem like a good idea, especially in the middle of PyCon CZ preparations).
2. We could ask @whit to change the DNS to the new values so the warning goes away.

**Comment by zhangyu1131** [comment]
I have the same warning. Are there any solution? Thank you!

**Comment by whit** [comment]
@honzajavorek Jsi si jist ze bych mel mit stale pristup k DNS nastaveni pro pyvec.org? Ja ve svych adminech vidim jen pyvec.cz a pyvec.com - CNAME na pyvec.org a nemam pristup do domena.cz. Prenastavim cokoli samozrejme, kdyz budu vedet co a jak a kde ;)

**Comment by honzajavorek** [comment]
@whit Tak se omlouvam, tvrzeni bylo na zaklade informaci od @encukou. Konecne jsem se prihlasil do domena.cz a:

1. v novem rozhrani jsem vubec nenasel nic co by naznacovalo ze lze prohlizet nebo editovat DNS
2. nastesti jsem nasel...

   <img width="804" alt="image" src="https://user-images.githubusercontent.com/283441/54608458-0351a700-4a51-11e9-9f6f-b50e81654ea2.png">

3. ve starem rozhrani lze s DNS normalne manipulovat

    <img width="484" alt="Screenshot 2019-03-19 at 14 13 31" src="https://user-images.githubusercontent.com/283441/54608534-3300af00-4a51-11e9-8320-6617bd6c325e.png">

4. jak jde ovsem videt, `A` zaznamy jsou jiz nastaveny na to, co je zde https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-a-records-with-your-dns-provider

Nevim, co mam dal delat.

**Comment by encukou** [comment]
Jo, na domena.cz je web nastavený správně (ale jiné záznamy, jako `MX`, ne).

Nameservery jsou ale aktuálně na `gransy.com`:

```console
$ dig -t NS pyvec.org
[...]
;; ANSWER SECTION:
pyvec.org.              1800    IN      NS      ns5.gransy.com.
pyvec.org.              1800    IN      NS      ns3.gransy.com.
pyvec.org.              1800    IN      NS      ns4.gransy.com.
pyvec.org.              1800    IN      NS      ns.gransy.com.
pyvec.org.              1800    IN      NS      ns2.gransy.com.
[...]
```

Co je `gransy` zač nevím, ale na Slacku je uvedeno „DNS Jižák (=@whit) ⌛“, tak předpokládám že to je tohle. Je to tak?

Před přepnutím bude potřeba urdělat transfer/sync, jinak se rozbije mail apod.

**Comment by honzajavorek** [comment]
Aha, tak to jsem nevedel. Gransy neznam, podle webu je to nejaky zizkovsky registrator. @whit-kuv jizak.cz ho pouziva taky, to asi nebude nahoda, i kdyz creatiweb.cz je teda na WEDOSu.

Asi by bylo nejlepsi tohle vzit jako prilezitost a prehazet to vsechno na IGNUM (domena.cz), aby v tom nebyl binec? Co je vlastne potreba pokud bychom to chteli prepnout? Staci pohlidat ten `MX` zaznam?

**Comment by encukou** [comment]
Je potřeba syncnout *všechny* záznamy. Ideálně přes [`AXFR`](https://en.wikipedia.org/wiki/DNS_zone_transfer) nebo jiný dump. Já na to asi nemám práva. V nejhorším by stačilo zkopírovat seznam poddomén z Gransy adminu, jestli se tam teda někdo dostane.
A pak pozměnit to, co chceme jinak (věci jako ty `A` které jsou na domena.cz správně).

**Comment by hroncok** [comment]
![_](https://user-images.githubusercontent.com/2401856/56773662-6a384d80-67bf-11e9-9f4a-887077014057.png)

Zatím nepíšou, kdy to vypnou, ale asi by bylo dobré s tím něco udělat. Nerozumím z konverzace, na kom/čem to vlastně visí. Ale předpokládám, že to nechceme hasit, až se to rozbije.

Souhrn:

 1. bez přístupu k účtu na Gransy nedokážeme spolehlivě zjistit seznam subdomén a tedy všechny záznamy - můžeme napsat třeba na jejich support?
 2. pokud vyřešíme 1., můžeme u registrátora domény změnit NS na doména.cz, ignum.cz nebo whatnot a nastavit si záznamy tam
 3. nevíme, kde změnit NS záznam, protože nsset je NSS:WD.JIZAK:1, ale @whit  tu doménu nevidí
 4. efektivně tedy tu doménu sice máme, ale DNS je navždy nepřístupné?

**Comment by honzajavorek** [comment]
Já se přiznám, že momentálně nemám kapacitu na tom pracovat. Jestli to chápu správně, nejlepší by bylo zjistit co je na současném DNS nastaveno (bod 1) a pak zmigrovat (bod 2). Je tedy potřeba začít emailem, nejlépe jménem Pyvce a s cc na info@pyvec.org.

To, co zmiňuješ v bodech 3 a 4 chápu jako popis současného smutného stavu, proč musíme jít přes body 1 a 2. Důležité také je, že @whit tu doménu nevidí, takže nám s tím asi nemá jak pomoci. Podle mě vznikl problém někde při převodu domény z Vítka na Pyvec, kdy se ti registrátoři a hostingy nějak nepopraly s dichotomií vlastníků.

**Comment by whit** [comment]
Ano, to bude hlavní problém že doménu jsme převedli pod jiného reg a vlastnictví jsme nechali. Je mi to líto, že je to tak komplikované. Když mi dáte přístup tam kde teď doména je - a lze-li tam nastavovat DNS tak bych snad se svým heslem mohl doménu upravit. Ale jist si tím vůbec nejsem.

V.

**Comment by whit** [comment]
Prolezl jsem starý admin na domena.cz a našel místo kde se to dalo upravit. Změny jsem autorizoval pomocí mailu vlastníka. Rovnou jsem upravil i domény .cz  a .com. Pro .cz doménu už mi přišlo potvrzení že změněno, generické domény asi budou trvat déle, ale je to autorizované. Prosím kontrolujte co se kde rozbije a DNS záznamy už můžete editovat sami, NS změněny.

**Comment by honzajavorek** [comment]
Vypadá to, že web i email snad fungují. @hroncok můžeš prosím ověřit, že "Page build warning" je pryč?

**Comment by hroncok** [comment]
Od 8.5. se žádný e-mail neobjevil.

**Comment by honzajavorek** [comment]
Tak jsme rozbili e-mail, současné MX záznamy míří na Ignum, ale my máme maily na GSuite. Řeším na Slacku, s GSuite neumím, ale snad to nějak opravíme a bude to dobrý. Toto issue týkající se webu zavírám.
