### ISSUE TITLE
Statický pyvec.org

### ISSUE THREAD

**Issue by encukou** [pyvec/pyvec.org#6]
Ahoj,
Statický web pyvec.org, založený na zdejší větvi `gh-pages`, je na https://encukou.github.io/pyvec.org/ . Kód je na https://github.com/encukou/pyvec.org .

Je to udělané přes Flask+Elsa, aby bylo možné použít šablony (pro jazykové verze) a Markdown. Deployment tohohle řešení, Git push→Travis→GH Pages, máme zmáknutý (pyladies.cz, naucse.python.cz).

Snažil jsem se to nastylovat celkem stroze (v podstatě čistý Bootstrap) a text cílit na sponzory a rozdavače grantovů, než na Pythoní komunitu – na tu máme barevnější python.cz. Nevím jak jsem v těchhle ohledech uspěl; editujte.

Nejsou tam věci jako:

* Projekty (http://pyvec.org/projekty/) – tohle přestalo být to, co Pyvec dělá (a podle toho ty projekty vypadají)
* Aktuální seznam akcí a odkazy na Lanyrd – místo toho tam je shrnutí toho nejdůležitějšího.

Zato tam je ale fungující odkaz na stanovy (https://github.com/pyvec/pyvec.org/issues/5), takže si myslím že svoji funkci by to už teď plnilo líp než původní stránky.

Sekci o podporovaných aktivitách by to chtělo před nasazením aktualizovat podle informací, co sbíráme kolem grantu, ať ty čísla aspoň trochu sedí.

Nedal jsem to jako Pull Request, protože tu chci *nahradit* větev master (a původní archivovat třeba jako `2012-ella-site`).

**Comment by martinbilek** [comment]
Petře, to je super!

Jen upozorním, že nějaká aktivita na předělání Pyvec webu už proběhla, tak jen aby to nezapadlo (@kvbik, @benabraham):
https://github.com/pyvec/pyvec.org/tree/gh-pages

+ ještě něco dělal podle mě @honzajavorek, ale už nevim, kde to přesně leží.

Každopádně tvoje verze mi přijde dobrá, určitě bych přidal alespoň logo a možná upravil barvy, ať to neni úplně mimo to, co lidi do teď znaji. Máš komu to zadat (minule si říkal o někom, koho máš na zaškolení) nebo to případně můžu zadat našemu kodérovi, aby si s tim pár hodin pohrál...

Každopádně už jen malej tuning a honem s tim ven :-)

Díííky!!!

**Comment by encukou** [comment]
Na zdejší větvi gh-pages je to založené. (Pak je tu ještě větev gh-pages-analytics, to bych řešil až po nasazení.)

Na vizuální stránku bohužel nikoho nemám, to bude lepší u vás. Přidal jsem README jak to spustit; struktura projektu snad je pochopitelná, kdyby ne tak se ptejte.

**Comment by benabraham** [comment]
To, co jsme dělali byl výstřel ve stylu MVP, tedy co minimálně tam **musí** bejt, aby se to dalo spustit. 

Mám pořád v bloku poznámky o dalších druzích uživatelů a jejich potřebách, co jsem vytahal z @honzajavorek ve Mšeným.

V každým případě se nemalujte s „grafikou“, prostě najdem hotový Bootstrap styl/téma, který zabrání tomu, aby to vypadalo nenastylovaný/výchozí Bootstrap.

Myslím, že bych tomu mohl i nějakej čas teď věnovat, pokud chcete.

**Comment by martinbilek** [comment]
Pokud bys na to měl čas teď/hned, bude to úplně super. Určitě bych taky nic nemaloval, jen to trochu obarvit a je to hotové. Co bych se přimlouval, tak je zkusit zachovat současné logo, ať alespoň držíme nějakou "linku".

**Comment by honzajavorek** [comment]
Neměl jsem čas se na to ještě podívat, ale řešíme https://github.com/pyvec/zapojse/issues/46 a ten se musí odevzdat do konce roku. Bylo by dobrý mít tohle v nějakém stavu nejpozději do konce roku.

**Comment by benabraham** [comment]
Vím o tom, momentálně jsem spíš vytíženej jinak. Když o tom tak dumám, tak by to chtělo domlátit za tenhel víkend…

**Comment by lspdv** [comment]
Mam z tohoto vlakna trochu pocit, jako by tu kazdy delal neco vlastniho :-) ze je to jen pocit, zejo zejo zejo zejo! :-) Kolegove pojdme spolupracovat! :-D

**Comment by honzajavorek** [comment]
Ja mam spis pocit, ze na to nikdo nemame ted cas, ale pocity se muzou
ruznit :) Kdyby se to nikam neposunulo, nasekam to nejak o Vanocich pred
terminem, poslepuju vsechno dohromady.

**Comment by encukou** [comment]
Kdyby to něco blokovalo, dá se použít to co tam je teď, mělo by stačit nastavit DNS.

K dodělání zbývá přidat logo a potunit barvičky.

**Comment by honzajavorek** [comment]
Jen tak pro info, kdo může měnit DNS? Martin Bílek nebo Vítek?

**Comment by martinbilek** [comment]
to musi vitek, domena je registrovana na nej...

**Comment by honzajavorek** [comment]
@encukou Přidáš logo a mergneš to? Barvičky dotuníme v nějakém jiném roce 😄 
Napíšeme pak @whit aby změnil DNS, to může taky trvat - třeba je někde na horách.

**Comment by whit** [comment]
Kdykoli kucí :)

**Comment by benabraham** [comment]
Tak kde to vázne? Šup.

**Comment by whit** [comment]
Dejte kdokoli info jak mam upravit DNS zaznamy pro pyvec.org pavec.com a pyvec.cz a ja to udelam, dokud mam cas a naladu :)

**Comment by lspdv** [comment]
@honzajavorek ted musi zachranit svet!!!!!

May the force be with us.

2016-12-31 12:18 GMT+01:00 Vítek Pliska <notifications@github.com>:

**Comment by benabraham** [comment]
@honzajavorek @encukou Můžu něco udělat? Nebo musíte vy? Potřebujem to nahodit.

**Comment by honzajavorek** [comment]
> Sekci o podporovaných aktivitách by to chtělo před nasazením aktualizovat podle informací, co sbíráme kolem grantu, ať ty čísla aspoň trochu sedí.

Jindy: https://github.com/pyvec/pyvec.org/issues/7

> Nedal jsem to jako Pull Request, protože tu chci *nahradit* větev master (a původní archivovat třeba jako `2012-ella-site`).

Hotovo.

**Comment by honzajavorek** [comment]
Zavírám https://github.com/pyvec/pyvec.org/issues/5, protože už je to v `master`.

**Comment by honzajavorek** [comment]
@whit Tak. Snad připraveno. Můžeš prosím nasměrovat doménu pyvec.org na GitHub Pages? Návod [zde](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/). Ostatní domény nejspíš přesměrovat na pyvec.org, ať je jen jedna hlavní.

**Comment by whit** [comment]
@honzajavorek mno, tak ja mam nak takhle:

    pyvec.org	        A             192.30.252.153
    pyvec.org	        A             192.30.252.154
    www.pyvec.org	CNAME	pyvec.org

a pro `.cz` a `.com` varianty sou tam dany `CNAME` na `pyvec.org` i pro `www.`. Je to tak nejak cca spravne? Ty navody sou dlouhy jak tejden, taky mohli kuci napsat hod A sem a CNAME sem :)

**Comment by whit** [comment]
Ale tak asi to nejak funguje. Skoda ze nejde poresit HTTPS ale jede to. Cau, mnau a dobrou.

**Comment by honzajavorek** [comment]
Jo, ty návody jsou hrozný. Mě to funguje. Paráda! Láska! ❤️ Díky! HTTPS doděláme jindy, jinak, nějak. Dokud tam není jediný `<input>`, je to jen obsese 😉

**Comment by lspdv** [comment]
Vitku, dekujeme!!! <3

2017-01-02 23:44 GMT+01:00 Honza Javorek <notifications@github.com>:
