### ISSUE TITLE
uBlock blokuje loga sponzorů

### ISSUE THREAD

**Issue by sairon** [pyvec/pyvec.org#9]
uBlock Origin (v1.10.4) v Chromiu blokuje při zapnutém "Cosmetic filtering" loga sponzorů. Nevím, zda to je nějakým patternem, který to matchne, nebo je v tom nějaká větší chytristika. Bylo by ale fajn, kdyby se loga neblokovala.

**Comment by encukou** [comment]
Vzhledem k tomu, že to používáš, asi bude na tobě zjustit proč se to děje.

**Comment by sairon** [comment]
Potvrzuje i @honzajavorek, změna class pomohla.
