### ISSUE TITLE
Fix the website on mobile phone

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvec.org#93]
The website doesn't render the best on a small phone, such as iPhone SE:

![IMG_3383](https://user-images.githubusercontent.com/283441/61822252-67e69d80-ae59-11e9-86df-db547aa071dc.PNG)

![IMG_3384](https://user-images.githubusercontent.com/283441/61822258-6b7a2480-ae59-11e9-9f5a-dfee71efbad2.PNG)

**Comment by torsava** [comment]
The issue still reproduces.
